// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	uow "pinstack-relation-service/internal/domain/ports/output/uow"

	mock "github.com/stretchr/testify/mock"
)

// UnitOfWork is an autogenerated mock type for the UnitOfWork type
type UnitOfWork struct {
	mock.Mock
}

type UnitOfWork_Expecter struct {
	mock *mock.Mock
}

func (_m *UnitOfWork) EXPECT() *UnitOfWork_Expecter {
	return &UnitOfWork_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function with given fields: ctx
func (_m *UnitOfWork) Begin(ctx context.Context) (uow.Transaction, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 uow.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (uow.Transaction, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) uow.Transaction); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uow.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UnitOfWork_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type UnitOfWork_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UnitOfWork_Expecter) Begin(ctx interface{}) *UnitOfWork_Begin_Call {
	return &UnitOfWork_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *UnitOfWork_Begin_Call) Run(run func(ctx context.Context)) *UnitOfWork_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *UnitOfWork_Begin_Call) Return(_a0 uow.Transaction, _a1 error) *UnitOfWork_Begin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UnitOfWork_Begin_Call) RunAndReturn(run func(context.Context) (uow.Transaction, error)) *UnitOfWork_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// NewUnitOfWork creates a new instance of UnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnitOfWork(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnitOfWork {
	mock := &UnitOfWork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
