env: "dev"

grpc_server:
  address: "0.0.0.0"
  port: 50054

database:
  username: "postgres"
  password: "admin"
  host: "relation-db"
  port: "5435"
  db_name: "relationservice"
  migrations_path: "./migrations"

kafka:
  brokers: "kafka1:9092,kafka2:9092,kafka3:9092"
  acks: "all"
  retries: 3
  retry_backoff_ms: 500
  delivery_timeout_ms: 5000
  queue_buffering_max_messages: 100000
  queue_buffering_max_ms: 5
  compression_type: "snappy"
  batch_size: 16384
  linger_ms: 5
  topic: "relation-events"

event_types:
  follow_created: "follow_created"
  follow_deleted: "follow_deleted"

user_service:
  address: "user-service"
  port: 50051

outbox:
  concurrency: 10
  tick_interval_ms: 2000
  batch_size: 100
