name: Relation Service CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go mod download

    - name: Run gofmt
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "Код не отформатирован:"
          gofmt -s -l .
          exit 1
        fi

    - name: Run go vet
      run: go vet ./...

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v7
      with:
        version: v2.2.2

    - name: Run unit tests
      run: go test -v -count=1 -race -coverprofile=coverage.txt ./...

    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.txt

  integration-tests:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout relation service
      uses: actions/checkout@v4

    - name: Checkout system tests
      uses: actions/checkout@v4
      with:
        repository: Soloda1/pinstack-system-tests
        path: pinstack-system-tests
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go mod download

    - name: Start Full Infrastructure for Integration Tests
      working-directory: pinstack-system-tests
      run: |
        # Запускаем все необходимые контейнеры для интеграционных тестов
        docker compose -f docker-compose.test.yml up -d \
          user-db-test \
          user-migrator-test \
          user-service-test \
          auth-db-test \
          auth-migrator-test \
          auth-service-test \
          api-gateway-test \
          notification-db-test \
          notification-migrator-test \
          notification-service-test \
          kafka-test \
          kafka-topics-init-test \
          relation-db-test \
          relation-migrator-test \
          relation-service-test

    - name: Wait for services to be ready
      run: |
        echo "⏳ Ожидание готовности сервисов..."
        
        # Ждем готовности баз данных
        timeout 60 bash -c 'until docker exec pinstack-user-db-test pg_isready -U postgres; do sleep 2; done'
        timeout 60 bash -c 'until docker exec pinstack-auth-db-test pg_isready -U postgres; do sleep 2; done'
        
        # Ждем готовности всех сервисов
        sleep 60
        
        # Проверяем, что все сервисы запустились
        echo "=== User Service logs ==="
        docker logs pinstack-user-service-test --tail=20
        echo "=== Auth Service logs ==="
        docker logs pinstack-auth-service-test --tail=20
        echo "=== Notification Service logs ==="
        docker logs pinstack-notification-service-test --tail=20
        echo "=== Relation Service logs ==="
        docker logs pinstack-relation-service-test --tail=20
        echo "=== API Gateway logs ==="
        docker logs pinstack-api-gateway-test --tail=20

    - name: Run relation-specific integration tests
      working-directory: pinstack-system-tests
      run: |
        echo "🧪 Запуск тестов для gateway_relation..."
        go test -v -count=1 -timeout=10m ./internal/scenarios/integration/gateway_relation/...

    - name: Collect logs on failure
      if: failure()
      working-directory: pinstack-system-tests
      run: |
        echo "=== Логи User Service ==="
        docker compose -f docker-compose.test.yml logs user-service-test
        echo "=== Логи User Migrator ==="
        docker compose -f docker-compose.test.yml logs user-migrator-test
        echo "=== Логи User Database ==="
        docker compose -f docker-compose.test.yml logs user-db-test
        echo "=== Логи Auth Service ==="
        docker compose -f docker-compose.test.yml logs auth-service-test
        echo "=== Логи Auth Migrator ==="
        docker compose -f docker-compose.test.yml logs auth-migrator-test
        echo "=== Логи Auth Database ==="
        docker compose -f docker-compose.test.yml logs auth-db-test
        echo "=== Логи Notification Service ==="
        docker compose -f docker-compose.test.yml logs notification-service-test
        echo "=== Логи Notification Migrator ==="
        docker compose -f docker-compose.test.yml logs notification-migrator-test
        echo "=== Логи Notification Database ==="
        docker compose -f docker-compose.test.yml logs notification-db-test
        echo "=== Логи Relation Service ==="
        docker compose -f docker-compose.test.yml logs relation-service-test
        echo "=== Логи Relation Migrator ==="
        docker compose -f docker-compose.test.yml logs relation-migrator-test
        echo "=== Логи Relation Database ==="
        docker compose -f docker-compose.test.yml logs relation-db-test
        echo "=== Логи Kafka ==="
        docker compose -f docker-compose.test.yml logs kafka-test
        echo "=== Логи Kafka Topics Init ==="
        docker compose -f docker-compose.test.yml logs kafka-topics-init-test
        echo "=== Логи API Gateway ==="
        docker compose -f docker-compose.test.yml logs api-gateway-test

    - name: Stop services
      if: always()
      working-directory: pinstack-system-tests
      run: |
        echo "🛑 Остановка всех сервисов..."
        docker compose -f docker-compose.test.yml down -v
        
        echo "🧹 Полная очистка Docker..."
        # Удаляем все остановленные контейнеры
        docker container prune -f
        # Удаляем все неиспользуемые образы
        docker image prune -a -f
        # Удаляем все неиспользуемые volume
        docker volume prune -f
        # Удаляем все неиспользуемые сети
        docker network prune -f
        
        echo "✅ Очистка завершена"